export const partners = [
  { id: "react", name: "React.js" },
  { id: "nextjs", name: "Next.js" },
  { id: "flutter", name: "Flutter" },
  { id: "reactnative", name: "React Native" },
  { id: "laravel", name: "Laravel" },
  { id: "shopify", name: "Shopify" },
  { id: "aws", name: "AWS" },
  { id: "microsoft", name: "Microsoft" },
  { id: "meta", name: "Meta" },
  { id: "vercel", name: "Vercel" },
  { id: "hostinger", name: "Hostinger" },
  { id: "paymob", name: "Paymob" },
  { id: "vue", name: "Vue.js" },
  { id: "nuxt", name: "Nuxt.js" },
  { id: "angular", name: "Angular" },
  { id: "zoom", name: "Zoom" },
  { id: "dotnet", name: ".NET" },
  { id: "django", name: "Django" },
  { id: "adobe", name: "Adobe" },
  { id: "wordpress", name: "WordPress" },
] as const;
